import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { Providers } from './components/Providers'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} relative bg-white text-black dark:bg-[#03001C] dark:selection:bg-[#03001C] dark:text-white min-h-screen selection:bg-gray-50 pb-10`}>
        
        <Providers>
        <Navbar/>
        <main className='max-w-3xl mx-auto px-4 sm:px-6 lg:px-8'>
          {children}
        </main>
        <Footer/>
        </Providers>
        
        
        
        </body>
    </html>
  )
}
